### ISSUE TITLE
Wrong coordinated when playing black

### ISSUE THREAD

**Issue by pnxdxt** [chesspecker/frontend#56]
Coordinates should be other way around when playing the black side

**Comment by pnxdxt** [comment]
Couldn't reproduce the bug

**Comment by pnxdxt** [comment]
Error happens when first puzzle is played from black side perspective

**Comment by t1u1** [comment]
I just now encountered this too!

The puzzle was https://lichess.org/training/NiXxX

And the solution (f5 g3) didn't make sense for a long time, until I realized that the co-ordinates were wrong.

**Comment by pnxdxt** [comment]
Implemented in the [new version](https://github.com/chesspecker/chesspecker)
