### ISSUE TITLE
Puzzles not being served

### ISSUE THREAD

**Issue by Sailias** [chesspecker/frontend#74]
OS: both ios and mac
Browser: mobile safari, mobile chrome, desktop chrome

reproduce: 

1. create set
2. Start
3. “Try to solve as fast as you can, start”
4. Board is in starting position with black to move 

it’s possible that my permissions are weird because I signed up before you removed the email requirement

**Comment by pnxdxt** [comment]
Hi, thanks for the the feedback 🔥

I was not aware of this issue and will look into it, doesn't look like a browser / compatibility issue since you kindly tried on multiple devices.

Could you share a screenshot of your console, might be helpful?

**Comment by Sailias** [comment]
There weren’t any console errors. I haven’t checked the API response yet, or forked it, stood it up, and debugged it myself yet.

**Comment by Sailias** [comment]
@pnxdxt the issue is validation when creating a set. You are able to create a set without selecting a mix of puzzles.
I will close this and create an appropriate issue
