### ISSUE TITLE
Show solution button does nothing (Android / Chrome) 

### ISSUE THREAD

**Issue by sttaffy** [chesspecker/frontend#81]
On mobile browser the show solution button is non-functional. When this site was first shown on reddit/r/chess it did work-it has since stopped working.

The progression section is also blank (no graphics or text). 

When using a desktop it works fine. 

Otherwise awesome tool!

**Comment by pnxdxt** [comment]
Thanks for letting us know!

@henribruvier Could you have a look at this?

**Comment by henribruvier** [comment]
I'm trying... really wird

**Comment by henribruvier** [comment]
fix in commit dec801e21760c048169d0a12da04fb4348719d2b
